
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postech-fiap.fullname" . }}-db-svc
spec:
  selector:
    #app: mongodb
    {{- include "postech-fiap.selectorLabels" . | nindent 4 }}
  type: NodePort
  ports:
    - port: 27017      
      targetPort: 27017
      nodePort: 30220
