apiVersion: v1
kind: Service
metadata:
  name: {{ include "postech-fiap.fullname" . }}-node-svc
spec:
  selector:
    #app: node-app
    {{- include "postech-fiap.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      nodePort: 31100
      port: 80
      targetPort: 3000
  type: NodePort