apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_DATABASE
          value: auth
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: pass
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: "init-database"
          mountPath: "/docker-entrypoint-initdb.d/"
        resources:
          requests:
            cpu: "0.1"
          limits:
            cpu: "0.2"
      volumes:
      - name: mongodb-data
      - name: "init-database"
        configMap:
          name: create-db-configmap
